/**
 * mapSpec.ts — declarative YAML schema for murrkit tile MAPS (Map Studio).
 *
 * Claude authors `phaser_game/maps/<id>.map.yaml`; `buildMapFromYAML` compiles
 * it into standard Tiled JSON deterministically and Phaser renders it natively.
 * Same philosophy as levelSpec: the YAML is the single source of truth, every
 * change is a whole-map rebuild from spec, so compounding regressions are
 * structurally impossible. A map is playable IMMEDIATELY — biomes without a
 * generated tileset render as deterministic placeholder colours, and swap to
 * real art the moment `/assets/tilesets/<project>/<biome>/sheet.png` exists.
 *
 * Tile-role convention (16-tile 4×4 sheet, generated by
 * `agents/asset_pipeline.generate_biome_tileset`, index = row-major):
 *
 *      0  1  2      TL  T  TR   ← edge tiles: transition on those sides
 *      3  4  5   =  L   C  R      (C = plain interior tile)
 *      6  7  8      BL  B  BR
 *      9 10 11      interior variants (subtle detail breakup)
 *     12 13 14 15   decor overlays (alpha; scattered on the decor layer)
 *
 * Projections: the LOGICAL grid (regions, paint, autotile roles, collision)
 * is identical in both. "orthogonal" (default) renders square T×T cells.
 * "isometric" renders true-iso 2:1 diamonds: `tileSize` is the diamond
 * HEIGHT, the diamond width is 2·tileSize, sheets are (2T)×T per cell.
 * Role sides map to diamond edges via Phaser's iso projection
 * (worldΔ of tile-N/E/S/W): N→top-right edge, E→bottom-right,
 * S→bottom-left, W→top-left.
 */

export const MAP_TILESET_COLUMNS = 4;
export const MAP_TILESET_ROWS = 4;
export const MAP_TILESET_TILECOUNT = MAP_TILESET_COLUMNS * MAP_TILESET_ROWS;

/** Row-major tile indices for the roles above. */
export const TILE = {
  TL: 0, T: 1, TR: 2,
  L: 3, C: 4, R: 5,
  BL: 6, B: 7, BR: 8,
  V1: 9, V2: 10, V3: 11,
  D0: 12, D1: 13, D2: 14, D3: 15,
} as const;

export interface BiomeTilesetSpec {
  /** Biome id referenced by regions, e.g. "grass". Declaration ORDER is the
   *  layering priority: later biomes sit "on top", so the earlier biome draws
   *  the transition edge along a shared border. */
  biome: string;
  /** Texture key. Defaults to `tiles_<biome>`. */
  key?: string;
  /** Sheet URL served by the game (e.g. `/assets/tilesets/default/grass/sheet.png`).
   *  Omit (or let it 404) → deterministic placeholder colours render instead,
   *  so the map is playtestable before any generation has run. */
  image?: string;
  /** Placeholder / minimap colour, e.g. "#4caf50". Defaults to a hash colour. */
  color?: string;
  /** false → the whole biome collides (water, lava, walls). Default true. */
  walkable?: boolean;
  /** 0..1 chance per interior cell of a decor overlay tile. Default 0. */
  decorDensity?: number;
}

export interface BiomeRegionSpec {
  biome: string;
  /** Rectangle in TILE coords [x, y, w, h]. Painted in list order (later wins). */
  rect?: [number, number, number, number];
  /** Voronoi seed point in TILE coords — cells not claimed by any rect go to
   *  the nearest seed. Mix rects (roads, lakes) with seeds (organic patches). */
  seed?: [number, number];
}

export interface MapObjectSpec {
  name: string;
  /** "spawn" places the playable avatar there; anything else is a marker
   *  exported to the Tiled object layer for game code to consume. */
  type?: string;
  /** TILE coords (fractions allowed: 12.5 = centre of column 12). */
  x: number;
  y: number;
}

/**
 * Per-cell paint layer — the RPG-Maker-style precision pass. Applied AFTER
 * `biomes` regions: any cell whose char maps to a biome overrides the
 * procedural base; "." (or an unmapped char) keeps it. Rows shorter than
 * `width` and missing trailing rows leave those cells untouched, so paint
 * diffs stay minimal. Both the Map Studio painter and the captain write this
 * block — it is plain text, so map edits stay git-diffable.
 */
export interface PaintSpec {
  /** single character → biome id declared in `tilesets` */
  legend: Record<string, string>;
  /** row-major strings, one char per cell, "." = no override */
  rows: string[];
}

export type MapProjection = "orthogonal" | "isometric";

/** Pixel size of one tile CELL under the spec's projection. Orthogonal:
 *  tileSize×tileSize squares. Isometric: 2:1 diamonds — width 2·tileSize,
 *  height tileSize (`tileSize: 32` → classic 64×32 rhombi). Single source of
 *  the 2:1 rule for the compiler, the scene, placeholders and sheet checks. */
export function tileDims(
  spec: Pick<MapSpec, "tileSize" | "projection">,
): { tileW: number; tileH: number } {
  return spec.projection === "isometric"
    ? { tileW: spec.tileSize * 2, tileH: spec.tileSize }
    : { tileW: spec.tileSize, tileH: spec.tileSize };
}

export interface MapSpec {
  id: string;
  /** Tile edge in px. Orthogonal: the square's side. Isometric: the diamond's
   *  HEIGHT (its width is always 2×this — see `tileDims`). */
  tileSize: number;
  /** "orthogonal" (default) = square top-down grid. "isometric" = true-iso
   *  2:1 diamond grid: same logical grid/regions/paint/roles, but the Tiled
   *  JSON is emitted with orientation "isometric" and tilesets use
   *  (2·tileSize)×tileSize cells. */
  projection?: MapProjection;
  /** Map size in TILES. */
  width: number;
  height: number;
  /** PRNG seed for variant/decor picks. Defaults to a hash of `id`. */
  seed?: number;
  /** Biome painted where nothing else claims a cell. Defaults to the first
   *  entry of `tilesets`. */
  defaultBiome?: string;
  tilesets: BiomeTilesetSpec[];
  biomes?: BiomeRegionSpec[];
  paint?: PaintSpec;
  objects?: MapObjectSpec[];
  notes?: string;
}

/** Fail-loud structural validation — bad YAML must never half-render. */
export function validateMapSpec(spec: unknown): asserts spec is MapSpec {
  const s = spec as Partial<MapSpec> | null;
  if (!s || typeof s !== "object") throw new Error("map spec: not an object");
  if (!s.id || typeof s.id !== "string") throw new Error("map spec: missing `id`");
  if (!Number.isInteger(s.width) || !Number.isInteger(s.height) ||
      (s.width as number) < 1 || (s.height as number) < 1) {
    throw new Error(`map '${s.id}': width/height must be positive integers (tiles)`);
  }
  if ((s.width as number) * (s.height as number) > 512 * 512) {
    throw new Error(`map '${s.id}': ${s.width}×${s.height} exceeds 512×512 tile cap`);
  }
  if (!Number.isInteger(s.tileSize) || (s.tileSize as number) < 8) {
    throw new Error(`map '${s.id}': tileSize must be an integer ≥ 8 px`);
  }
  if (s.projection !== undefined && s.projection !== "orthogonal" && s.projection !== "isometric") {
    throw new Error(`map '${s.id}': projection must be "orthogonal" or "isometric"`);
  }
  if (!Array.isArray(s.tilesets) || s.tilesets.length === 0) {
    throw new Error(`map '${s.id}': needs at least one entry in \`tilesets\``);
  }
  const biomeNames = new Set<string>();
  for (const t of s.tilesets) {
    if (!t.biome) throw new Error(`map '${s.id}': tileset entry without \`biome\``);
    if (biomeNames.has(t.biome)) throw new Error(`map '${s.id}': duplicate tileset biome '${t.biome}'`);
    biomeNames.add(t.biome);
  }
  for (const r of s.biomes ?? []) {
    if (!biomeNames.has(r.biome)) {
      throw new Error(`map '${s.id}': region references unknown biome '${r.biome}' (declare it in \`tilesets\`)`);
    }
    if (!r.rect && !r.seed) {
      throw new Error(`map '${s.id}': region for '${r.biome}' needs \`rect\` or \`seed\``);
    }
  }
  if (s.defaultBiome && !biomeNames.has(s.defaultBiome)) {
    throw new Error(`map '${s.id}': defaultBiome '${s.defaultBiome}' not declared in \`tilesets\``);
  }
  if (s.paint !== undefined) {
    const p = s.paint as Partial<PaintSpec> | null;
    if (!p || typeof p !== "object" || !p.legend || typeof p.legend !== "object" || !Array.isArray(p.rows)) {
      throw new Error(`map '${s.id}': \`paint\` needs \`legend\` (char→biome) and \`rows\` (strings)`);
    }
    for (const [ch, b] of Object.entries(p.legend)) {
      if (ch.length !== 1 || ch === ".") {
        throw new Error(`map '${s.id}': paint legend key '${ch}' must be a single char (not '.')`);
      }
      if (typeof b !== "string" || !biomeNames.has(b)) {
        throw new Error(`map '${s.id}': paint legend '${ch}' → unknown biome '${b}'`);
      }
    }
    if (p.rows.length > (s.height as number)) {
      throw new Error(`map '${s.id}': paint has ${p.rows.length} rows but map height is ${s.height}`);
    }
    for (let y = 0; y < p.rows.length; y++) {
      const row = p.rows[y];
      if (typeof row !== "string") throw new Error(`map '${s.id}': paint row ${y} is not a string`);
      if (row.length > (s.width as number)) {
        throw new Error(`map '${s.id}': paint row ${y} is ${row.length} chars but map width is ${s.width}`);
      }
      for (const ch of row) {
        if (ch !== "." && p.legend[ch] === undefined) {
          throw new Error(`map '${s.id}': paint row ${y} uses char '${ch}' missing from legend`);
        }
      }
    }
  }
}

/** Deterministic fallback colour for a biome with no explicit `color`. */
export function biomeColor(t: BiomeTilesetSpec): number {
  if (t.color) {
    const hex = t.color.replace("#", "");
    const n = parseInt(hex.length === 3 ? hex.split("").map((c) => c + c).join("") : hex, 16);
    if (!Number.isNaN(n)) return n;
  }
  // FNV-1a over the biome name → stable hue; fixed s/l keeps it readable.
  let h = 0x811c9dc5;
  for (let i = 0; i < t.biome.length; i++) {
    h ^= t.biome.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return hslToRgbInt(((h >>> 0) % 360), 0.45, 0.45);
}

function hslToRgbInt(hDeg: number, s: number, l: number): number {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const hp = hDeg / 60;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  const [r1, g1, b1] =
    hp < 1 ? [c, x, 0] : hp < 2 ? [x, c, 0] : hp < 3 ? [0, c, x] :
    hp < 4 ? [0, x, c] : hp < 5 ? [x, 0, c] : [c, 0, x];
  const m = l - c / 2;
  const to255 = (v: number): number => Math.round((v + m) * 255);
  return (to255(r1) << 16) | (to255(g1) << 8) | to255(b1);
}
